language: shell
os: linux

env:
  global:
    - NODE_VERSION=16
    - CC_TEST_REPORTER_ID=46ef31dae5b656e0f4be410a86bd83bdcf73e7d27ab33a704c197e6fe4bf02a0
    - DOCKER_CLI_EXPERIMENTAL=enabled

before_install:

  - export IMAGE_VERSION=${TRAVIS_BRANCH//\//\_}
  - export IMAGE_VERSION=${IMAGE_VERSION//\#/\_}

  # Install docker with buildx
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - lsb_release -cs
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
  - cat /proc/sys/fs/binfmt_misc/qemu-aarch64

  # Install Nodejs
  - nvm install $NODE_VERSION

  # Init Code Climate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./app/cc-test-reporter
  - (cd app && chmod +x ./cc-test-reporter)
  - (cd app && ./cc-test-reporter before-build)

install:

  # Install dependencies
  - (cd app && npm ci)
  - (cd e2e && npm ci)
  - (cd ui && npm ci)

  # Run Linter
  - (cd app && npm run lint)
  - (cd e2e && npm run lint)
  - (cd ui && npm run lint)

  # Run UT
  - (cd app && npm test)

  # Package ui
  - (cd ui && npm run build)

  # Build wud docker image
  - docker build -t wud --build-arg WUD_VERSION=$IMAGE_VERSION .

script:

  # Pull nginx as a test image
  - docker pull nginx:1.10-alpine
  - docker pull nginx:1.20-alpine

  # Tag nginx 1.10 as latest to simulate an update_available
  - docker tag nginx:1.10-alpine nginx:latest

  # Tag nginx as if it was coming from private Hub, ECR, GCR, ACR...
  - docker tag nginx:1.10-alpine fmartinou/test:1.0.0
  - docker tag nginx:1.10-alpine 229211676173.dkr.ecr.eu-west-1.amazonaws.com/test:1.0.0
  - docker tag nginx:1.10-alpine 229211676173.dkr.ecr.eu-west-1.amazonaws.com/sub/test:1.0.0
  - docker tag nginx:1.10-alpine 229211676173.dkr.ecr.eu-west-1.amazonaws.com/sub/sub/test:1.0.0
#  - docker tag nginx:1.10-alpine gcr.io/wud-test/test:1.0.0
#  - docker tag nginx:1.10-alpine gcr.io/wud-test/sub/test:1.0.0
#  - docker tag nginx:1.10-alpine gcr.io/wud-test/sub/sub/test:1.0.0
#  - docker tag nginx:1.10-alpine wudtest.azurecr.io/test:1.0.0
#  - docker tag nginx:1.10-alpine wudtest.azurecr.io/sub/test:1.0.0
#  - docker tag nginx:1.10-alpine wudtest.azurecr.io/sub/sub/test:1.0.0

  # Pull homeassistant
  - docker pull homeassistant/home-assistant
  - docker pull homeassistant/home-assistant:2021.6.1

  # Pull omnidb
  - docker pull omnidbteam/omnidb

  # Pull pihole
  - docker pull pihole/pihole
  - docker pull pihole/pihole:v5.7

  # Pull pyload
  - docker pull writl/pyload

  # Pull traefik
  - docker pull traefik
  - docker pull traefik:2.4.5

  # Pull vaultwarden
  - docker pull vaultwarden/server
  - docker pull vaultwarden/server:1.22.2-alpine

  # Pull youtubedl
  - docker pull jeeaaasustest/youtube-dl

  # Run containers for tests

  # ACR
  #  - docker run -d --name acr_test          --label "wud.watch=true" wudtest.azurecr.io/test:1.0.0
  #  - docker run -d --name acr_sub_test      --label "wud.watch=true" wudtest.azurecr.io/sub/test:1.0.0
  #  - docker run -d --name acr_sub_sub_test  --label "wud.watch=true" wudtest.azurecr.io/sub/sub/test:1.0.0

  # ECR
  - docker run -d --name ecr_sub_sub_test --label 'wud.watch=true' 229211676173.dkr.ecr.eu-west-1.amazonaws.com/sub/sub/test:1.0.0
  - docker run -d --name ecr_sub_test     --label 'wud.watch=true' 229211676173.dkr.ecr.eu-west-1.amazonaws.com/sub/test:1.0.0
  - docker run -d --name ecr_test         --label 'wud.watch=true' 229211676173.dkr.ecr.eu-west-1.amazonaws.com/test:1.0.0

  # GCR
  #  - docker run -d --name gcr_test          --label "wud.watch=true" gcr.io/wud-test/test:1.0.0
  #  - docker run -d --name gcr_sub_test      --label "wud.watch=true" gcr.io/wud-test/sub/test:1.0.0
  #  - docker run -d --name gcr_sub_sub_test  --label "wud.watch=true" gcr.io/wud-test/sub/sub/test:1.0.0

  # GHCR
  - docker run -d --name ghcr_radarr              --label 'wud.watch=true' --label 'wud.tag.include=^\d+\.\d+\.\d+\.\d+-ls\d+$'               ghcr.io/linuxserver/radarr:3.2.1.5070-ls105

  # HUB
  - docker run -d --name hub_homeassistant_202161 --label 'wud.watch=true' --label 'wud.tag.include=^\d+\.\d+.\d+$'                           homeassistant/home-assistant:2021.6.1
  - docker run -d --name hub_homeassistant_latest --label 'wud.watch=true' --label 'wud.watch.digest=true' --label 'wud.tag.include=^latest$' homeassistant/home-assistant

  - docker run -d --name hub_nginx_120            --label 'wud.watch=true' --label 'wud.tag.include=^\d+\.\d+-alpine$'                        nginx:1.20-alpine
  - docker run -d --name hub_nginx_latest         --label 'wud.watch=true' --label 'wud.watch.digest=true' --label 'wud.tag.include=^latest$' nginx

  - docker run -d --name hub_omnidb_latest        --label 'wud.watch=true' --label 'wud.watch.digest=true' --label 'wud.tag.include=^latest$' omnidbteam/omnidb

  - docker run -d --name hub_pihole_57            --label 'wud.watch=true' --label 'wud.tag.include=^v\d+\.\d+.\d+$'                          pihole/pihole:v5.7
  - docker run -d --name hub_pihole_latest        --label 'wud.watch=true' --label 'wud.watch.digest=true' --label 'wud.tag.include=^latest$' pihole/pihole

  - docker run -d --name hub_pyload_latest        --label 'wud.watch=true' --label 'wud.watch.digest=true' --label 'wud.tag.include=^latest$' writl/pyload

#  - docker run -d --name hub_test                 --label 'wud.watch=true' --label 'wud.tag.include=^\d+\.\d+.\d+$'                           fmartinou/test:1.0.0

  - docker run -d --name hub_traefik_245          --label 'wud.watch=true' --label 'wud.tag.include=^\d+\.\d+.\d+$'                           traefik:2.4.5
  - docker run -d --name hub_traefik_latest       --label 'wud.watch=true' --label 'wud.watch.digest=true' --label 'wud.tag.include=^latest$' traefik

  - docker run -d --name hub_vaultwarden_1222     --label 'wud.watch=true' --label 'wud.tag.include=^\d+\.\d+.\d+-alpine$'                    vaultwarden/server:1.22.2-alpine
  - docker run -d --name hub_vaultwarden_latest   --label 'wud.watch=true' --label 'wud.watch.digest=true' --label 'wud.tag.include=^latest$' vaultwarden/server

  - docker run -d --name hub_youtubedb_latest     --label 'wud.watch=true' --label 'wud.watch.digest=true' --label 'wud.tag.include=^latest$' jeeaaasustest/youtube-dl

  # Run wud docker image
  - >
    docker run -d
    --name wud
    --publish 3000:3000
    --volume /var/run/docker.sock:/var/run/docker.sock
    --env WUD_TRIGGER_MOCK_EXAMPLE_MOCK=mock
    --env WUD_WATCHER_LOCAL_WATCHBYDEFAULT=false
    --env WUD_REGISTRY_ACR_CLIENTID="$ACR_CLIENT_ID"
    --env WUD_REGISTRY_ACR_CLIENTSECRET="$ACR_CLIENT_SECRET"
    --env WUD_REGISTRY_ECR_ACCESSKEYID="$AWS_ACCESSKEY_ID"
    --env WUD_REGISTRY_ECR_SECRETACCESSKEY="$AWS_SECRET_ACCESSKEY"
    --env WUD_REGISTRY_ECR_REGION=eu-west-1
    --env WUD_REGISTRY_GCR_CLIENTEMAIL="$GCR_CLIENT_EMAIL"
    --env WUD_REGISTRY_GCR_PRIVATEKEY="$GCR_PRIVATE_KEY"
    --env WUD_REGISTRY_GHCR_USERNAME=""
    --env WUD_REGISTRY_GHCR_TOKEN=""
    --env WUD_REGISTRY_HUB_AUTH=""
    --env WUD_LOG_LEVEL="debug"
    wud

  #    --env WUD_REGISTRY_HUB_LOGIN="$DOCKER_USERNAME"
  #    --env WUD_REGISTRY_HUB_TOKEN="$DOCKER_PASSWORD"

  # Give wud a little time to fetch all available updates
  - sleep 20

  - docker container logs wud

  # Run E2E Tests
  - (cd e2e && npm run cucumber)

after_failure:
  # Display wud logs
  - docker container logs wud

after_success:

  # Report to Code Climate
  - (cd app && ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT)

  # Override image version with latest if master branch
  - if [ "$TRAVIS_BRANCH" == "master" ] ; then export IMAGE_VERSION=latest; fi

  # Override image version with tag name if any
  - if [ ! -z "$TRAVIS_TAG" ] ; then export IMAGE_VERSION=$TRAVIS_TAG; fi

  # Build & push image
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker version
  - make prepare
  - make build IMAGE_NAME=$DOCKER_USERNAME/whats-up-docker IMAGE_VERSION=$IMAGE_VERSION PLATFORMS=linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64
